module.exports.data = [
  {
    extendPortTotalPrevious15MinDnDiscByteCounter: 'Down Discard Byte',
    extendPortTotalPrevious15MinDnDiscFrameCounter: 'Down Discard Frame',
    extendPortTotalPrevious15MinDnFwdByteCounter: 'Down Foward Byte',
    extendPortTotalPrevious15MinDnFwdFrameCounter: 'Down Foward Frame',
    extendPortTotalPrevious15MinTimeMeasured: 'Time Measured',
    extendPortTotalPrevious15MinUpDiscByteCounter: 'Up Discard Byte',
    extendPortTotalPrevious15MinUpDiscFrameCounter: 'Up Discard Frame',
    extendPortTotalPrevious15MinUpFwdByteCounter: 'Up Foward Byte',
    extendPortTotalPrevious15MinUpFwdFrameCounter: 'Up Foward Frame',
  },
  {
    gponOntOntsideAggGemIntervalReceiveBlocksCounter64: 'Recieve Blocks',
    gponOntOntsideAggGemIntervalReceiveFrags: 'Receive Frags',
    gponOntOntsideAggGemIntervalTransmitBlocksCounter64: 'Transmit Blocks',
    gponOntOntsideAggGemIntervalTransmitFrags: 'Transmit Frags',
  },
  {
    extendPortVlanPrevious15MinDnDiscByteCounter: 'Down Discard Byte',
    extendPortVlanPrevious15MinDnDiscFrameCounter: 'Down Discard Frame',
    extendPortVlanPrevious15MinDnFwdByteCounter: 'Down Foward Byte',
    extendPortVlanPrevious15MinDnFwdFrameCounter: 'Down Foward Frame',
    extendPortVlanPrevious15MinUpDiscByteCounter: 'Up Discard Byte',
    extendPortVlanPrevious15MinUpDiscFrameCounter: 'Up Discard Frame',
    extendPortVlanPrevious15MinUpFwdByteCounter: 'Up Foward Byte',
    extendPortVlanPrevious15MinUpFwdFrameCounter: 'Up Foward Frame',
  },
  {
    extendPortVlanCurrent1DayDnDiscByteCounter: 'Down Discard Byte',
    extendPortVlanCurrent1DayDnFwdByteCounter: 'Down Foward Byte',
    extendPortVlanCurrent1DayUpDiscByteCounter: 'Up Discard Byte',
    extendPortVlanCurrent1DayUpFwdByteCounter: 'Up Foward Byte',
  },
  {
    extendPortTotalDnDiscByteCounter: 'Down Discard Byte',
    extendPortTotalDnFwdByteCounter: 'Down Foward Byte',
    extendPortTotalUpDiscByteCounter: 'Up Discard Byte',
    extendPortTotalUpFwdByteCounter: 'Up Foward Byte',
    ifOperStatus: 'interface Operation Status',
  },
  {
    ifAdminStatus: 'interface Administration Status',
    ifOperStatus: 'interface Operation Status',
  },
  {
    ifAdminStatus: 'interface Administration Status',
    ifOperStatus: 'interface Operation Status',
  },
  {
    asamIfExtCustomerId: 'Ext Customer ID',
    ifAdminStatus: 'interface Administration Status',
    ifOperStatus: 'interface Operation Status',
  },
  {
    bponOntEquipId: 'Equipment ID',
    bponOntSerialNumber: 'Serial Number',
    bponOntSubscriberId1: 'Suscriber ID1',
    bponOntSubscriberLocId: 'Suscriber Location ID',
    ifAdminStatus: 'interface Administration Status',
    ifOperStatus: 'interface Operation Status',
  },
  {
    extendEtherPortStatisticsIfInDiscards: 'interface Ingress Discards',
    extendEtherPortStatisticsIfInNUcastPkts: 'interface NU cast Packets',
    extendEtherPortStatisticsIfInOctets: 'interface Ingress Octets',
    extendEtherPortStatisticsIfOutDiscards: 'interface Outgress Discards',
    extendEtherPortStatisticsIfOutNUcastPkts:
      'interface Outgress NU cast Packets',
    extendEtherPortStatisticsIfOutOctets: 'Interface Outgress Octets',
    ifAdminStatus: 'interface Administration Status',
    ifHighSpeed: 'interface High Speed',
    ifOperStatus: 'interface Operation Status',
  },
  {
    memAbsoluteUsage: 'memory Absolute Usage',
    operateStatus: 'operation Status',
    startMonitorTime: 'start Monitor Time',
    totalMemSize: 'total memory size',
  },
  {
    ifHCInOctets: 'interface HC Ingress Octetes',
    ifHCOutOctets: 'interface HC Outgress Octetes',
    ifInDiscards: 'interface ingress Discards',
    ifOutDiscards: 'interface outgress Discards',
    ' tmnxPortAdminStatus': 'tmnx Port Admin Status',
    tmnxPortEtherOperSpeed: 'tmnx Port Ether operat Status',
    tmnxPortEtherSpeed: 'tmnx Port Ether Speed',
    tmnxPortLinkStatus: 'tmnx Port Link Status',
    tmnxPortOperStatus: 'tmnx Port operat Status',
  },
  {
    extendPortVlanCurrent1DayDnDiscByteCounter: 'Down Discard Byte',
    extendPortVlanCurrent1DayDnFwdByteCounter: 'Down Foward Byte',
    extendPortVlanCurrent1DayUpDiscByteCounter: 'Up Discard Byte',
    extendPortVlanCurrent1DayUpFwdByteCounter: 'Up Foward Byte',
  },
]
